Public Class Class2
    Public Shared Establishment As String
    Public Shared NameOfBusiness As String
    Public Shared AddressWork As String
    Public Shared NumOfEmploymentMale As String
    Public Shared NumofEmploymentFemale As String
    Public Shared TotalEmployees As String
    Public Shared Manager As String
    Public Shared Name As String
    Public Shared Age As String
    Public Shared Sex As String
    Public Shared CivilStatus As String
    Public Shared Address As String
    Public Shared Position As String
    Public Shared PhoneNum As String
    Public Shared Religion As String
    Public Shared Nationality As String
    Public Shared ExperienceOfOccupation As String
    Public Shared NumOfDependents As String
    Public Shared BirthDate As String
    Public Shared MonthlyWage As String
    Public Shared WorkshiftAM As String
    Public Shared WorkshiftPM As String
    Public Shared HoursOfWorkDay As String
    Public Shared Week As String
    Public Shared EmergencyNum As String
    Public Shared Relationship As String
    Public Shared Phone As String
    Public Shared Agency As String
    Public Shared AgencyAddress As String
    Public Shared ChiefComplaints As String
    Public Shared HealthHx As String
    Public Shared MedsTaken As String
    Public Shared Allergies As String
    Public Shared Medicine As String
    Public Shared Food As String
    Public Shared BP As String
    Public Shared RR As String
    Public Shared PR As String
    Public Shared Temperature As String
    Public Shared O2Sat As String
    Public Shared Wt As String
    Public Shared Ht As String
    Public Shared BMI As String
    Public Shared Remarks As String
    Public Shared LMP As String
    Public Shared NameOfIncident As String
    Public Shared PlaceOfIncident As String
    Public Shared DateOfIncident As String
    Public Shared DateOfDisabilityBegan As String
    Public Shared PartOfTheBodyAffected
    Public Shared TimeOfIncident As String
    Public Shared TypeOfIncident As String
    Public Shared PropertyDamage As String
    Public Shared PersonalInjury As String
    Public Shared DateOfReturnedToWork As String
    Public Shared DayLost As String
    Public Shared UnsafeAct As String
    Public Shared UnsafeMechanical As String
    Public Shared ContributingFactor As String
    Public Shared ExtentOfDisability As String
    Public Shared DamageOfProperty As String
    Public Shared DescriptionOfIncident As String
    Public Shared Witness As String
End Class
